GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/blogs/62bab2c4991393fb4c7093e6

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYWxldiIsImlkIjoiNjJjNTM5ZDM0ZjllNTdhMTE1OTg1NTY5IiwiaWF0IjoxNjU3MTc5NDM5LCJleHAiOjE2NTcxODMwMzl9.jZbaoZJ9hJPfXBfEW8D8E3kQD7JHZM4ewXMq_YC52so

{
    "title": "Culinary blog",
    "author": "Ada Levitski",
    "url": "http://Culinary",
    "likes": 1234,
    "userId": "62c539d34f9e57a115985569"
}

###
DELETE http://localhost:3003/api/blogs/62c589ae908d79f34ff13e62 HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYWxldiIsImlkIjoiNjJjNTM5ZDM0ZjllNTdhMTE1OTg1NTY5IiwiaWF0IjoxNjU3MTc5NDM5LCJleHAiOjE2NTcxODMwMzl9.jZbaoZJ9hJPfXBfEW8D8E3kQD7JHZM4ewXMq_YC52so

###
PUT http://localhost:3003/api/blogs/62bab33c991393fb4c7093e9 HTTP/1.1
content-type: application/json

{
    "likes": 101
}