GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/blogs/62bab2c4991393fb4c7093e6

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "Culinary blog",
    "author": "Ada Levitski",
    "url": "http://Culinary",
    "likes": 12,
    "userId": "62c539d34f9e57a115985569"
}

###
DELETE http://localhost:3003/api/blogs/62c44ad950fadc7b96381f5e HTTP/1.1
content-type: application/json

###
PUT http://localhost:3003/api/blogs/62bab33c991393fb4c7093e9 HTTP/1.1
content-type: application/json

{
    "likes": 101
}